Repository Our-Leaders/our-leaders-api, pull requests merged in 2019-11, with the labels that each got.

#2 #12731076: model users
  models/User.js
  models/index.js
Labels: enhancement

#3 #12730269: model political parties
  models/PoliticalParty.js
  models/index.js
Labels: enhancement

#6 #12731319: add sign up
  .env.example
  config/Config.js
  controllers/Auth.js
  models/User.js
  package.json
  routes/AuthRoutes.js
  routes/index.js
  utils/FacebookUtil.js
  utils/GoogleUtil.js
  utils/OutputFormatters.js
  validators/AuthValidators.js
  yarn.lock
Labels: feature

#7 #12731320 Registered user
  controllers/Auth.js
  routes/AuthRoutes.js
  validators/AuthValidators.js
Labels: in code review

#8 #12732982: authentication middleware
  controllers/Auth.js
  middleware/AuthenticationMiddleware.js
Labels: feature

#10 #12732984: admin create political party
  config/Config.js
  controllers/PoliticalParties.js
  middleware/ImageMiddleware.js
  models/PoliticalParty.js
  package.json
  routes/PoliticalPartyRoutes.js
  utils/ImageUtil.js
  utils/OutputFormatters.js
  validators/PoliticalPartyValidators.js
  yarn.lock
Labels: enhancement, feature

#13 #12735133: subscribe to politician
  controllers/Politician.js
  controllers/Subscriptions.js
  models/Subscription.js
  models/index.js
  routes/SubscriptionRoutes.js
  routes/index.js
  validators/SubscriptionValidators.js
Labels: feature

#19 #12735414: add politician professional background
  controllers/Politician.js
  routes/politicianRoutes.js
  validators/PoliticianValidators.js
Labels: enhancement

#21 #12738058: update political party model
  controllers/PoliticalParties.js
  models/PoliticalParty.js
  utils/OutputFormatters.js
  utils/errorUtil.js
Labels: enhancement

#23 #12744867: retrieve feeds
  config/Config.js
  controllers/Subscriptions.js
  cron/CronScheduler.js
  cron/FeedsJob.js
  models/Feed.js
  models/Subscription.js
  models/index.js
  package.json
  server.js
  yarn.lock
Labels: feature
